[package]
name = "rusty-p4"
version = "0.1.0"
authors = ["skye"]
edition = "2018"
build=false

[dependencies]
prost = "0.5"
grpcio = "0.5.0-alpha.4"
rusty-p4-proto = {path="../rusty-p4-proto"}
futures = "^0.1.15"
byteorder = "1.3.2"
libc = "0.2"
hex = "0.3"
tokio = { version="0.2.0-alpha.2" , features = ["rt-full"] }
bytes = "0.4.12"
futures03 = { package="futures-preview", version = "0.3.0-alpha.18", features = ["async-await", "nightly", "compat"]}
# hyper = { git="https://github.com/hyperium/hyper.git", optional = true }
log = "0.4"
flexi_logger = "0.13.2"
bitfield = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ctrlc = { version = "3.0", features = ["termination"] }
failure = "0.1.5"
smallvec = "0.6"